apiVersion: v1
kind: Pod
metadata:
  name: emp-demo2
spec:
  containers:
  - name: app2
    image: nginx
    volumeMounts:
    - mountPath: /cache
      name: scratch-space
  volumes:
  - name: scratch-space
    emptyDir:
      sizeLimit: 500Mi
