apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers: 
      - name: mycon
        image: hashicorp/http-echo:0.2.3
        ports:
        - containerPort: 80


