apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels: 
    app: ustapp
  namespace: customns
spec:
  containers:
  - name: firstcon
    image: rajcosivadevops/ustimage:latest
    ports: 
    - containerPort: 80
